
git:
    add($pattern):
        do: poetry run git add $pattern
        after: poetry run pre-commit

    commit($message):
        before: poetry run pre-commit
        do: poetry run git commit -m $pattern



